# Some handy keys
## Panel nav - alt + o, p , [, ] (down, up, left, right)
bind -n M-[ select-pane -L
bind -n M-] select-pane -R
bind -n M-o select-pane -D
bind -n M-p select-pane -U

## window nav Ctrl + `, space (prev, next)
bind -n -r M-Space next-window
bind -n -r C-M-Space previous-window

## Resizing panels - alt + shift + o, p , [, ] (down, up, left, right)
bind -n -r M-\{ resize-pane -L
bind -n -r M-\} resize-pane -R
bind -n -r M-O resize-pane -D
bind -n -r M-P resize-pane -U

## Making panels and windows - alt + ', ; (split vertical, horizontal)
## alt + n (new window)
## alt + shift + ' (kill panel)
## alt + shift + n (kill window)
bind -n M-\' split-window -v
bind -n M-\; split-window -h
bind -n M-n new-window
bind -n M-\" killp
bind -n M-N killw

#Binding prefixes (default + Alt-`)
set-option -g prefix C-b
set-option -g prefix2 M-`

# One-second clock updates (Default 15)
# Doesn't work unless you reload source manually - bit annoying.
# set-option -s status-interval 1

# Increase status-right length so the clock fits (Default 40)
set -g status-right-length 120

# Sets Battery + time as right status. No need to worry about a seperator as my quick 'n' dirty direct use of acpi_readout script adds it as a side-effect...
# oops, broke this migrating to usb. Must've had some acpi_readout script or something, can't be bothered remaking it at the moment.
set -g status-right '#{battery_percentage}%a %h-%d %H:%M ' # :%S'no more seconds :)

# Runs battery percentage thingo
run-shell ~/utils/tmux-battery/battery.tmux

# Enable xterm keys (for shift+arrow keys etc...)
set -g xterm-keys on

# Set global terminal mode to the good one
set -g default-terminal "tmux-256color"

# Get clipboard working
set -as terminal-features ',tmux-256color:clipboard'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Init TMUX Plugin manager
run '~/.tmux/plugins/tpm/tpm'

